### ISSUE TITLE
Filestructure

### ISSUE THREAD

**Issue by MrGallo** [ICS2O-Gallo/10c-cpt-amin-and-danny#3]
If you are not using the branching features of GitHub, please have the repository conform to the proper file structure.
```
cpt-group-names (repository)
        |
        |- development (Folder)
                |
                |- cpt.py
        |- master (Folder)
                |
                |- cpt.py
        |- README.md
```

**Comment by AminHoss** [comment]
So do we put our incomplete in a development folder, and game and asset folders in a master folder. Or are you asking us to create a new branch called development?

**Comment by MrGallo** [comment]
Is this resolved with the branches?

**Comment by AminHoss** [comment]
No not yet. Still have replace master branch content with master1 content. I'll do it at home
